### PR TITLE
5948/remove q interval from indexers query

### PR DESCRIPTION
**Pull request by kayvank**
Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense and have useful messages
    - [ ] Important changes are reflected in changelog.d of the affected packages
    - [ ] Relevant tickets are mentioned in commit messages
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [ ] Targeting main unless this is a cherry-pick backport
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] If relevant, reference the ADR in the PR and reference the PR in the ADR
    - [ ] Reviewer requested

### CODE REVIEW

**Review by berewt — APPROVED** [review]
LGTM
We may want to amend the corresponding ADR, but not sure if it needs to be done in this story. What do you think about it @koslambrou ?

**Comment by koslambrou** [comment]
@berewt The ADR in `plutus-apps` repo? If so, yeah I think it should be amended.

**Comment by berewt** [comment]
> @berewt The ADR in `plutus-apps` repo? If so, yeah I think it should be amended.

Yes, should we consider having an ADR folder for Marconi as well by the way?

**Comment by koslambrou** [comment]
@berewt Yep. Once we need to write one, we'll add it here and migrate the existing ones from plutus-apps here.

**Comment by kayvank** [comment]
> @berewt Yep. Once we need to write one, we'll add it here and migrate the existing ones from plutus-apps here.

Here are the links to plutus-apps [PR](https://github.com/input-output-hk/plutus-apps/pull/1073) and corresponding JIRA [ticket](https://input-output.atlassian.net/browse/PLT-6004)

**Pull request merged**
