### PR TITLE
PLT-6279 Add Txinputs to the results of the utxo query

### PR DESCRIPTION
**Pull request by berewt**
We add a `UtxoQueryResult` type to ease the deserialisation of SQL result.

To get all the TxInputs in one sql row, we need to provide an hexadecimal representation of the txid and to concatenate them as string, and to decipher them on the Haskell side.

Pre-submit checklist:
- Branch
    - [x] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense and have useful messages
    - [ ] Important changes are reflected in changelog.d of the affected packages
    - [ ] Relevant tickets are mentioned in commit messages
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [x] Targeting main unless this is a cherry-pick backport
    - [ ] Self-reviewed the diff
    - [x] Useful pull request description
    - [ ] If relevant, reference the ADR in the PR and reference the PR in the ADR
    - [x] Reviewer requested

### CODE REVIEW

**Comment by eyeinsky** [comment]
This is already added as part of #35 which has resolved datums included.

**Comment by berewt** [comment]
> This is already added as part of #35 which has resolved datums included.

Are you sure? The objective here is to include the list of inputs (TxIn) that were spent when creating an utxo. I had a quick look at #35 and I didn't see anything related to it.

**Comment by eyeinsky** [comment]
> > This is already added as part of #35 which has resolved datums included.
> 
> Are you sure? The objective here is to include the list of inputs (TxIn) that were spent when creating an utxo. I had a quick look at #35 and I didn't see anything related to it.

Ah, right, I meant the UtxoResult type itself. The list of `TxIn` in it is new yes. Would it be possible to rebase this onto the other branch? Merging in main and resolving conflicts is error prone..

**Comment by berewt** [comment]
Aren't rebasing it on the datum branch or waiting for the datum branch to hit main and then rebasing the same risk? If I wait for the other part to hit main, at least I won't have to rebase after each new commit to the datum branch (I'm ok with the idea of waiting the datum merge before merging mine).

**Comment by eyeinsky** [comment]
Yes, there will be merge conflicts either way, it's just that this one seemed more contained (or maybe it's not, I don't know..).

Anyway, I've already made few new bugs into my branch when merging main, it's always a ton of extra work with no added value. Would be easier to either not work on the same area, or start off from the other person's branch.

**Pull request closed without merging**
