### PR TITLE
PLT-8135 Avoid showing log messages in help output

### PR DESCRIPTION
**Pull request by neilmayhew**
As discussed in today's grooming session.

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense and have useful messages
    - [ ] Important changes are reflected in changelog.d of the affected packages
    - [x] Relevant tickets are mentioned in commit messages
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [x] Targeting main unless this is a cherry-pick backport
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [ ] If relevant, reference the ADR in the PR and reference the PR in the ADR
    - [x] Reviewer requested

### CODE REVIEW

**Comment by neilmayhew** [comment]
The Darwin builds failed due to a segfault. I think this is an ongoing problem not related to this PR.

**Review by berewt — APPROVED** [review]
LGTM. Can you create another ticket to add the version in the help message (or do it in this one)?

**Comment by berewt** [comment]
> The Darwin builds failed due to a segfault. I think this is an ongoing problem not related to this PR.

Yes, we'll probably want to disable the Darwin build for the tutorial if it continue to build that often.

**Review by willjgould — APPROVED** [review]
This makes sense to me!

**Comment by neilmayhew** [comment]
> Can you create another ticket to add the version in the help message (or do it in this one)?

As agreed in the tech discussion, we won't do that now

**Pull request merged**
