### PR TITLE
Updated the CONTRIBUTING file and renamed the `__std__` directory to nix

### PR DESCRIPTION
**Pull request by koslambrou**
Move `__std__` to `nix` to follow the same convention as plutus and plutus-apps repos.

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense and have useful messages
    - [ ] Important changes are reflected in changelog.d of the affected packages
    - [ ] Relevant tickets are mentioned in commit messages
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [ ] Targeting main unless this is a cherry-pick backport
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] If relevant, reference the ADR in the PR and reference the PR in the ADR
    - [ ] Reviewer requested

### CODE REVIEW

**Review by berewt — COMMENTED** [review]
LGTM, do you want to be the unique contact point for documentation and CI? (I don't have a problem with it but we can share the burden within the team if you want).

**Comment by koslambrou** [comment]
@berewt Good point. I'd like to keep documentation, but CI can definitely be someone else. Initially, it was zeme-iohk, but he's not part of the team anymore. Suggestions?

Maybe you and I on documentation, and @kayvank and I on CI?

**Comment by berewt** [comment]
I can't speak on Kayvan's behalf, but I can help on the documentation (again, if it's fine for you).

**Comment by kayvank** [comment]
> @berewt Good point. I'd like to keep documentation, but CI can definitely be someone else. Initially, it was zeme-iohk, but he's not part of the team anymore. Suggestions?
> 
> Maybe you and I on documentation, and @kayvank and I on CI?

I would very interested in the CI work and documentation as well as needed

**Comment by koslambrou** [comment]
@berewt Ready to review

**Review by berewt — APPROVED** [review]
LGTM 👍

**Pull request merged**
